[package]
name = "{{ project-name }}"
version = "0.0.0"
authors = ["{{ username }}"]
repository = "https://github.com/{{ github }}/{{ project-name }}/"
license = "{{ license }}"
categories = []
keywords = []
edition = "2021"
rust-version = "1.74"
publish = false
