[package]
name = "{{ project-name }}"
version = "0.0.0"
authors = ["{{ username }}"]
repository = ""
license = "{{ license }}"
categories = []
keywords = []
edition = "2024"
rust-version = "1.85"
publish = false
