[package]
name = "rust-template"
version = "0.0.0"
authors = ["Lieselotte <52315535+she3py@users.noreply.github.com>"]
repository = "https://github.com/ShE3py/rust-template/"
license = "MIT"
categories = []
keywords = []
edition = "2024"
rust-version = "1.85"
publish = false
