[package]
name = "{{ project-name }}"
version = "0.0.0"
authors = ["{{ username }}"]
repository.workspace = true
license.workspace = true
categories = []
keywords = []
edition.workspace = true
rust-version = "1.74"
publish = false
