[build]
rustflags = [
	# Written for rustc 1.91.0-nightly (1ed3cd703 2025-09-06)
    "-Faarch64_softfloat_neon", "-Wambiguous_negative_literals", "-Wclippy::alloc_instead_of_core",
    "-Wclippy::allow_attributes", "-Fclippy::as_pointer_underscore", "-Fclippy::as_underscore",
    "-Wclippy::assigning_clones", "-Wclippy::bool_to_int_with_if", "-Fclippy::borrow_as_ptr",
    "-Wclippy::case_sensitive_file_extension_comparisons", "-Dclippy::cast_possible_truncation",
    "-Fclippy::cast_possible_wrap", "-Wclippy::cast_precision_loss", "-Fclippy::cast_ptr_alignment",
    "-Wclippy::checked_conversions", "-Wclippy::clear_with_drain", "-Wclippy::clone_on_ref_ptr",
    "-Wclippy::cloned_instead_of_copied", "-Wclippy::coerce_container_to_any", "-Wclippy::collection_is_never_read",
    "-Wclippy::comparison_chain", "-Wclippy::copy_iterator", "-Wclippy::debug_assert_with_mut_call",
    "-Wclippy::decimal_literal_representation", "-Fclippy::default_trait_access", "-Wclippy::default_union_representation",
    "-Wclippy::derive_partial_eq_without_eq", "-Wclippy::doc_broken_link", "-Fclippy::doc_comment_double_space_linebreaks",
    "-Wclippy::doc_include_without_cfg", "-Wclippy::elidable_lifetime_names", "-Wclippy::else_if_without_else",
    "-Wclippy::equatable_if_let", "-Wclippy::expl_impl_clone_on_copy", "-Wclippy::field_scoped_visibility_modifiers",
    "-Wclippy::filetype_is_file", "-Wclippy::filter_map_next", "-Wclippy::flat_map_option", "-Wclippy::format_collect",
    "-Wclippy::format_push_string", "-Wclippy::future_not_send", "-Wclippy::get_unwrap",
    "-Wclippy::if_then_some_else_none", "-Fclippy::ignore_without_reason", "-Wclippy::ignored_unit_patterns",
    "-Fclippy::implicit_clone", "-Wclippy::implicit_hasher", "-Wclippy::imprecise_flops",
    "-Wclippy::inconsistent_struct_constructor", "-Wclippy::index_refutable_slice", "-Wclippy::indexing_slicing",
    "-Wclippy::inefficient_to_string", "-Wclippy::into_iter_without_iter", "-Wclippy::invalid_upcast_comparisons",
    "-Wclippy::ip_constant", "-Wclippy::iter_filter_is_ok", "-Wclippy::iter_filter_is_some",
    "-Wclippy::iter_not_returning_iterator", "-Wclippy::iter_on_empty_collections", "-Wclippy::iter_on_single_items",
    "-Wclippy::iter_with_drain", "-Wclippy::iter_without_into_iter", "-Wclippy::large_digit_groups",
    "-Wclippy::large_futures", "-Wclippy::large_stack_arrays", "-Wclippy::large_stack_frames",
    "-Wclippy::large_types_passed_by_value", "-Wclippy::lossy_float_literal", "-Wclippy::manual_instant_elapsed",
    "-Wclippy::manual_is_power_of_two", "-Wclippy::manual_is_variant_and", "-Wclippy::manual_let_else",
    "-Wclippy::manual_midpoint", "-Wclippy::manual_string_new", "-Wclippy::map_err_ignore", "-Wclippy::map_unwrap_or",
    "-Wclippy::map_with_unused_argument_over_ranges", "-Wclippy::match_wildcard_for_single_variants",
    "-Wclippy::mismatching_type_param_order", "-Wclippy::missing_asserts_for_indexing", "-Wclippy::missing_const_for_fn",
    "-Wclippy::mixed_read_write_in_expression", "-Wclippy::module_name_repetitions", "-Wclippy::multiple_crate_versions",
    "-Fclippy::multiple_unsafe_ops_per_block", "-Wclippy::mut_mut", "-Wclippy::mutex_atomic", "-Wclippy::mutex_integer",
    "-Wclippy::needless_bitwise_bool", "-Wclippy::needless_collect", "-Wclippy::needless_for_each",
    "-Wclippy::needless_pass_by_ref_mut", "-Wclippy::needless_pass_by_value", "-Wclippy::needless_raw_string_hashes",
    "-Wclippy::needless_raw_strings", "-Fclippy::negative_feature_names", "-Wclippy::no_effect_underscore_binding",
    "-Wclippy::no_mangle_with_rust_abi", "-Dclippy::non_send_fields_in_send_ty", "-Wclippy::non_std_lazy_statics",
    "-Wclippy::non_zero_suggestions", "-Wclippy::nonstandard_macro_braces", "-Wclippy::option_as_ref_cloned",
    "-Wclippy::option_if_let_else", "-Wclippy::option_option", "-Wclippy::path_buf_push_overwrite",
    "-Fclippy::precedence_bits", "-Fclippy::ptr_as_ptr", "-Fclippy::ptr_cast_constness", "-Wclippy::pub_underscore_fields",
    "-Wclippy::pub_without_shorthand", "-Wclippy::range_minus_one", "-Wclippy::range_plus_one", "-Wclippy::rc_buffer",
    "-Wclippy::rc_mutex", "-Wclippy::read_zero_byte_vec", "-Wclippy::redundant_clone",
    "-Wclippy::redundant_closure_for_method_calls", "-Fclippy::redundant_feature_names", "-Wclippy::redundant_test_prefix",
    "-Wclippy::redundant_type_annotations", "-Fclippy::ref_as_ptr", "-Wclippy::ref_option", "-Wclippy::ref_option_ref",
    "-Wclippy::renamed_function_params", "-Wclippy::rest_pat_in_fully_bound_structs",
    "-Wclippy::same_functions_in_if_condition", "-Fclippy::self_named_module_files",
    "-Fclippy::semicolon_if_nothing_returned", "-Fclippy::semicolon_outside_block", "-Wclippy::set_contains_or_insert",
    "-Wclippy::should_panic_without_expect", "-Wclippy::significant_drop_in_scrutinee",
    "-Wclippy::significant_drop_tightening", "-Wclippy::single_char_lifetime_names", "-Wclippy::single_char_pattern",
    "-Wclippy::single_option_map", "-Wclippy::stable_sort_primitive", "-Wclippy::str_split_at_newline",
    "-Fclippy::str_to_string", "-Fclippy::string_add_assign", "-Wclippy::string_lit_as_bytes", "-Wclippy::string_slice",
    "-Wclippy::suboptimal_flops", "-Wclippy::suspicious_operation_groupings", "-Wclippy::tests_outside_test_module",
    "-Wclippy::too_long_first_doc_paragraph", "-Wclippy::trailing_empty_array", "-Wclippy::trait_duplication_in_bounds",
    "-Wclippy::transmute_ptr_to_ptr", "-Wclippy::transmute_undefined_repr", "-Wclippy::trivial_regex",
    "-Wclippy::trivially_copy_pass_by_ref", "-Fclippy::try_err", "-Wclippy::tuple_array_conversions",
    "-Wclippy::type_repetition_in_bounds", "-Wclippy::undocumented_unsafe_blocks", "-Wclippy::unicode_not_nfc",
    "-Fclippy::uninhabited_references", "-Wclippy::uninlined_format_args", "-Wclippy::unnecessary_box_returns",
    "-Wclippy::unnecessary_debug_formatting", "-Wclippy::unnecessary_join", "-Wclippy::unnecessary_literal_bound",
    "-Wclippy::unnecessary_safety_comment", "-Wclippy::unnecessary_safety_doc", "-Wclippy::unnecessary_self_imports",
    "-Wclippy::unnecessary_struct_initialization", "-Wclippy::unnecessary_wraps", "-Wclippy::unnested_or_patterns",
    "-Wclippy::unsafe_derive_deserialize", "-Fclippy::unseparated_literal_suffix", "-Wclippy::unused_async",
    "-Wclippy::unused_peekable", "-Wclippy::unused_result_ok", "-Wclippy::unused_rounding", "-Wclippy::unused_self",
    "-Wclippy::unused_trait_names", "-Wclippy::used_underscore_binding", "-Wclippy::used_underscore_items",
    "-Wclippy::useless_let_if_seq", "-Wclippy::verbose_file_reads", "-Fclippy::wildcard_dependencies",
    "-Wclippy::zero_sized_map_values", "-Wclosure_returning_async_block", "-Wderef_into_dyn_supertrait",
    "-Welided_lifetimes_in_paths", "-Wexplicit_outlives_requirements", "-Wffi_unwind_calls",
    "-Wimpl_trait_redundant_captures", "-Wlet_underscore_drop", "-Wlinker_messages", "-Wmeta_variable_misuse",
    "-Wmissing_copy_implementations", "-Wmissing_debug_implementations", "-Wredundant_imports", "-Wredundant_lifetimes",
    "-Wsingle_use_lifetimes", "-Wtrivial_casts", "-Wtrivial_numeric_casts", "-Wunit_bindings", "-Wunnameable_types",
    "-Wunreachable_pub", "-Wunused_crate_dependencies", "-Wunused_extern_crates", "-Wunused_import_braces",
    "-Wunused_lifetimes", "-Wunused_macro_rules", "-Wunused_qualifications",
]
