[workspace]
members = [
    "{{ project-name }}",
]
resolver = "2"

[workspace.package]
repository = "https://github.com/{{ github }}/{{ project-name }}/"
license = "MIT OR Apache-2.0"
edition = "2021"
