[placeholders.github]
type = "string"
prompt = "GitHub username (or organization)"
regex = "^[A-Za-z0-9][A-Za-z0-9-]{0,38}$"

[conditional.'crate_type == "lib"']
ignore = ["{{ project-name }}/src/main.rs"]
